package com.cibr.InsectRecognition.entity;

public class CibrSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.userStatus
     *
     * @mbggenerated
     */
    private String userstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.roleType
     *
     * @mbggenerated
     */
    private String roletype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.id
     *
     * @return the value of cibr_sys_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.id
     *
     * @param id the value for cibr_sys_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.name
     *
     * @return the value of cibr_sys_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.name
     *
     * @param name the value for cibr_sys_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.email
     *
     * @return the value of cibr_sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.email
     *
     * @param email the value for cibr_sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.password
     *
     * @return the value of cibr_sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.password
     *
     * @param password the value for cibr_sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.userStatus
     *
     * @return the value of cibr_sys_user.userStatus
     *
     * @mbggenerated
     */
    public String getUserstatus() {
        return userstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.userStatus
     *
     * @param userstatus the value for cibr_sys_user.userStatus
     *
     * @mbggenerated
     */
    public void setUserstatus(String userstatus) {
        this.userstatus = userstatus == null ? null : userstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.roleType
     *
     * @return the value of cibr_sys_user.roleType
     *
     * @mbggenerated
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.roleType
     *
     * @param roletype the value for cibr_sys_user.roleType
     *
     * @mbggenerated
     */
    public void setRoletype(String roletype) {
        this.roletype = roletype == null ? null : roletype.trim();
    }
}