package com.cibr.InsectRecognition.entity;

import java.util.ArrayList;
import java.util.List;

public class CibrSysTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public CibrSysTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVdomainIsNull() {
            addCriterion("vdomain is null");
            return (Criteria) this;
        }

        public Criteria andVdomainIsNotNull() {
            addCriterion("vdomain is not null");
            return (Criteria) this;
        }

        public Criteria andVdomainEqualTo(String value) {
            addCriterion("vdomain =", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainNotEqualTo(String value) {
            addCriterion("vdomain <>", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainGreaterThan(String value) {
            addCriterion("vdomain >", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainGreaterThanOrEqualTo(String value) {
            addCriterion("vdomain >=", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainLessThan(String value) {
            addCriterion("vdomain <", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainLessThanOrEqualTo(String value) {
            addCriterion("vdomain <=", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainLike(String value) {
            addCriterion("vdomain like", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainNotLike(String value) {
            addCriterion("vdomain not like", value, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainIn(List<String> values) {
            addCriterion("vdomain in", values, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainNotIn(List<String> values) {
            addCriterion("vdomain not in", values, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainBetween(String value1, String value2) {
            addCriterion("vdomain between", value1, value2, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVdomainNotBetween(String value1, String value2) {
            addCriterion("vdomain not between", value1, value2, "vdomain");
            return (Criteria) this;
        }

        public Criteria andVkingdomIsNull() {
            addCriterion("vkingdom is null");
            return (Criteria) this;
        }

        public Criteria andVkingdomIsNotNull() {
            addCriterion("vkingdom is not null");
            return (Criteria) this;
        }

        public Criteria andVkingdomEqualTo(String value) {
            addCriterion("vkingdom =", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomNotEqualTo(String value) {
            addCriterion("vkingdom <>", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomGreaterThan(String value) {
            addCriterion("vkingdom >", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomGreaterThanOrEqualTo(String value) {
            addCriterion("vkingdom >=", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomLessThan(String value) {
            addCriterion("vkingdom <", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomLessThanOrEqualTo(String value) {
            addCriterion("vkingdom <=", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomLike(String value) {
            addCriterion("vkingdom like", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomNotLike(String value) {
            addCriterion("vkingdom not like", value, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomIn(List<String> values) {
            addCriterion("vkingdom in", values, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomNotIn(List<String> values) {
            addCriterion("vkingdom not in", values, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomBetween(String value1, String value2) {
            addCriterion("vkingdom between", value1, value2, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVkingdomNotBetween(String value1, String value2) {
            addCriterion("vkingdom not between", value1, value2, "vkingdom");
            return (Criteria) this;
        }

        public Criteria andVphylumIsNull() {
            addCriterion("vphylum is null");
            return (Criteria) this;
        }

        public Criteria andVphylumIsNotNull() {
            addCriterion("vphylum is not null");
            return (Criteria) this;
        }

        public Criteria andVphylumEqualTo(String value) {
            addCriterion("vphylum =", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumNotEqualTo(String value) {
            addCriterion("vphylum <>", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumGreaterThan(String value) {
            addCriterion("vphylum >", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumGreaterThanOrEqualTo(String value) {
            addCriterion("vphylum >=", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumLessThan(String value) {
            addCriterion("vphylum <", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumLessThanOrEqualTo(String value) {
            addCriterion("vphylum <=", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumLike(String value) {
            addCriterion("vphylum like", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumNotLike(String value) {
            addCriterion("vphylum not like", value, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumIn(List<String> values) {
            addCriterion("vphylum in", values, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumNotIn(List<String> values) {
            addCriterion("vphylum not in", values, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumBetween(String value1, String value2) {
            addCriterion("vphylum between", value1, value2, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVphylumNotBetween(String value1, String value2) {
            addCriterion("vphylum not between", value1, value2, "vphylum");
            return (Criteria) this;
        }

        public Criteria andVclassIsNull() {
            addCriterion("vclass is null");
            return (Criteria) this;
        }

        public Criteria andVclassIsNotNull() {
            addCriterion("vclass is not null");
            return (Criteria) this;
        }

        public Criteria andVclassEqualTo(String value) {
            addCriterion("vclass =", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassNotEqualTo(String value) {
            addCriterion("vclass <>", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassGreaterThan(String value) {
            addCriterion("vclass >", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassGreaterThanOrEqualTo(String value) {
            addCriterion("vclass >=", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassLessThan(String value) {
            addCriterion("vclass <", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassLessThanOrEqualTo(String value) {
            addCriterion("vclass <=", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassLike(String value) {
            addCriterion("vclass like", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassNotLike(String value) {
            addCriterion("vclass not like", value, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassIn(List<String> values) {
            addCriterion("vclass in", values, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassNotIn(List<String> values) {
            addCriterion("vclass not in", values, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassBetween(String value1, String value2) {
            addCriterion("vclass between", value1, value2, "vclass");
            return (Criteria) this;
        }

        public Criteria andVclassNotBetween(String value1, String value2) {
            addCriterion("vclass not between", value1, value2, "vclass");
            return (Criteria) this;
        }

        public Criteria andVorderIsNull() {
            addCriterion("vorder is null");
            return (Criteria) this;
        }

        public Criteria andVorderIsNotNull() {
            addCriterion("vorder is not null");
            return (Criteria) this;
        }

        public Criteria andVorderEqualTo(String value) {
            addCriterion("vorder =", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderNotEqualTo(String value) {
            addCriterion("vorder <>", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderGreaterThan(String value) {
            addCriterion("vorder >", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderGreaterThanOrEqualTo(String value) {
            addCriterion("vorder >=", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderLessThan(String value) {
            addCriterion("vorder <", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderLessThanOrEqualTo(String value) {
            addCriterion("vorder <=", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderLike(String value) {
            addCriterion("vorder like", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderNotLike(String value) {
            addCriterion("vorder not like", value, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderIn(List<String> values) {
            addCriterion("vorder in", values, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderNotIn(List<String> values) {
            addCriterion("vorder not in", values, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderBetween(String value1, String value2) {
            addCriterion("vorder between", value1, value2, "vorder");
            return (Criteria) this;
        }

        public Criteria andVorderNotBetween(String value1, String value2) {
            addCriterion("vorder not between", value1, value2, "vorder");
            return (Criteria) this;
        }

        public Criteria andVfamilyIsNull() {
            addCriterion("vfamily is null");
            return (Criteria) this;
        }

        public Criteria andVfamilyIsNotNull() {
            addCriterion("vfamily is not null");
            return (Criteria) this;
        }

        public Criteria andVfamilyEqualTo(String value) {
            addCriterion("vfamily =", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyNotEqualTo(String value) {
            addCriterion("vfamily <>", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyGreaterThan(String value) {
            addCriterion("vfamily >", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyGreaterThanOrEqualTo(String value) {
            addCriterion("vfamily >=", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyLessThan(String value) {
            addCriterion("vfamily <", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyLessThanOrEqualTo(String value) {
            addCriterion("vfamily <=", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyLike(String value) {
            addCriterion("vfamily like", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyNotLike(String value) {
            addCriterion("vfamily not like", value, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyIn(List<String> values) {
            addCriterion("vfamily in", values, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyNotIn(List<String> values) {
            addCriterion("vfamily not in", values, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyBetween(String value1, String value2) {
            addCriterion("vfamily between", value1, value2, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVfamilyNotBetween(String value1, String value2) {
            addCriterion("vfamily not between", value1, value2, "vfamily");
            return (Criteria) this;
        }

        public Criteria andVgenusIsNull() {
            addCriterion("vgenus is null");
            return (Criteria) this;
        }

        public Criteria andVgenusIsNotNull() {
            addCriterion("vgenus is not null");
            return (Criteria) this;
        }

        public Criteria andVgenusEqualTo(String value) {
            addCriterion("vgenus =", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusNotEqualTo(String value) {
            addCriterion("vgenus <>", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusGreaterThan(String value) {
            addCriterion("vgenus >", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusGreaterThanOrEqualTo(String value) {
            addCriterion("vgenus >=", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusLessThan(String value) {
            addCriterion("vgenus <", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusLessThanOrEqualTo(String value) {
            addCriterion("vgenus <=", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusLike(String value) {
            addCriterion("vgenus like", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusNotLike(String value) {
            addCriterion("vgenus not like", value, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusIn(List<String> values) {
            addCriterion("vgenus in", values, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusNotIn(List<String> values) {
            addCriterion("vgenus not in", values, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusBetween(String value1, String value2) {
            addCriterion("vgenus between", value1, value2, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVgenusNotBetween(String value1, String value2) {
            addCriterion("vgenus not between", value1, value2, "vgenus");
            return (Criteria) this;
        }

        public Criteria andVspeciesIsNull() {
            addCriterion("vspecies is null");
            return (Criteria) this;
        }

        public Criteria andVspeciesIsNotNull() {
            addCriterion("vspecies is not null");
            return (Criteria) this;
        }

        public Criteria andVspeciesEqualTo(String value) {
            addCriterion("vspecies =", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesNotEqualTo(String value) {
            addCriterion("vspecies <>", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesGreaterThan(String value) {
            addCriterion("vspecies >", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesGreaterThanOrEqualTo(String value) {
            addCriterion("vspecies >=", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesLessThan(String value) {
            addCriterion("vspecies <", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesLessThanOrEqualTo(String value) {
            addCriterion("vspecies <=", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesLike(String value) {
            addCriterion("vspecies like", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesNotLike(String value) {
            addCriterion("vspecies not like", value, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesIn(List<String> values) {
            addCriterion("vspecies in", values, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesNotIn(List<String> values) {
            addCriterion("vspecies not in", values, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesBetween(String value1, String value2) {
            addCriterion("vspecies between", value1, value2, "vspecies");
            return (Criteria) this;
        }

        public Criteria andVspeciesNotBetween(String value1, String value2) {
            addCriterion("vspecies not between", value1, value2, "vspecies");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}