package com.cibr.InsectRecognition.entity;

public class CibrSysType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vdomain
     *
     * @mbggenerated
     */
    private String vdomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vkingdom
     *
     * @mbggenerated
     */
    private String vkingdom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vphylum
     *
     * @mbggenerated
     */
    private String vphylum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vclass
     *
     * @mbggenerated
     */
    private String vclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vorder
     *
     * @mbggenerated
     */
    private String vorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vfamily
     *
     * @mbggenerated
     */
    private String vfamily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vgenus
     *
     * @mbggenerated
     */
    private String vgenus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_type.vspecies
     *
     * @mbggenerated
     */
    private String vspecies;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.id
     *
     * @return the value of cibr_sys_type.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.id
     *
     * @param id the value for cibr_sys_type.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vdomain
     *
     * @return the value of cibr_sys_type.vdomain
     *
     * @mbggenerated
     */
    public String getVdomain() {
        return vdomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vdomain
     *
     * @param vdomain the value for cibr_sys_type.vdomain
     *
     * @mbggenerated
     */
    public void setVdomain(String vdomain) {
        this.vdomain = vdomain == null ? null : vdomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vkingdom
     *
     * @return the value of cibr_sys_type.vkingdom
     *
     * @mbggenerated
     */
    public String getVkingdom() {
        return vkingdom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vkingdom
     *
     * @param vkingdom the value for cibr_sys_type.vkingdom
     *
     * @mbggenerated
     */
    public void setVkingdom(String vkingdom) {
        this.vkingdom = vkingdom == null ? null : vkingdom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vphylum
     *
     * @return the value of cibr_sys_type.vphylum
     *
     * @mbggenerated
     */
    public String getVphylum() {
        return vphylum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vphylum
     *
     * @param vphylum the value for cibr_sys_type.vphylum
     *
     * @mbggenerated
     */
    public void setVphylum(String vphylum) {
        this.vphylum = vphylum == null ? null : vphylum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vclass
     *
     * @return the value of cibr_sys_type.vclass
     *
     * @mbggenerated
     */
    public String getVclass() {
        return vclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vclass
     *
     * @param vclass the value for cibr_sys_type.vclass
     *
     * @mbggenerated
     */
    public void setVclass(String vclass) {
        this.vclass = vclass == null ? null : vclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vorder
     *
     * @return the value of cibr_sys_type.vorder
     *
     * @mbggenerated
     */
    public String getVorder() {
        return vorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vorder
     *
     * @param vorder the value for cibr_sys_type.vorder
     *
     * @mbggenerated
     */
    public void setVorder(String vorder) {
        this.vorder = vorder == null ? null : vorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vfamily
     *
     * @return the value of cibr_sys_type.vfamily
     *
     * @mbggenerated
     */
    public String getVfamily() {
        return vfamily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vfamily
     *
     * @param vfamily the value for cibr_sys_type.vfamily
     *
     * @mbggenerated
     */
    public void setVfamily(String vfamily) {
        this.vfamily = vfamily == null ? null : vfamily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vgenus
     *
     * @return the value of cibr_sys_type.vgenus
     *
     * @mbggenerated
     */
    public String getVgenus() {
        return vgenus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vgenus
     *
     * @param vgenus the value for cibr_sys_type.vgenus
     *
     * @mbggenerated
     */
    public void setVgenus(String vgenus) {
        this.vgenus = vgenus == null ? null : vgenus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_type.vspecies
     *
     * @return the value of cibr_sys_type.vspecies
     *
     * @mbggenerated
     */
    public String getVspecies() {
        return vspecies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_type.vspecies
     *
     * @param vspecies the value for cibr_sys_type.vspecies
     *
     * @mbggenerated
     */
    public void setVspecies(String vspecies) {
        this.vspecies = vspecies == null ? null : vspecies.trim();
    }
}