package com.cibr.InsectRecognition.entity;

import java.util.Date;

public class CibrBussIdentify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.vadress
     *
     * @mbggenerated
     */
    private String vadress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.animalId
     *
     * @mbggenerated
     */
    private String animalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.filePath
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.openId
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.altitude
     *
     * @mbggenerated
     */
    private String altitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.recstatus
     *
     * @mbggenerated
     */
    private String recstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_buss_identify.fileId
     *
     * @mbggenerated
     */
    private String fileid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.id
     *
     * @return the value of cibr_buss_identify.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.id
     *
     * @param id the value for cibr_buss_identify.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.vadress
     *
     * @return the value of cibr_buss_identify.vadress
     *
     * @mbggenerated
     */
    public String getVadress() {
        return vadress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.vadress
     *
     * @param vadress the value for cibr_buss_identify.vadress
     *
     * @mbggenerated
     */
    public void setVadress(String vadress) {
        this.vadress = vadress == null ? null : vadress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.animalId
     *
     * @return the value of cibr_buss_identify.animalId
     *
     * @mbggenerated
     */
    public String getAnimalid() {
        return animalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.animalId
     *
     * @param animalid the value for cibr_buss_identify.animalId
     *
     * @mbggenerated
     */
    public void setAnimalid(String animalid) {
        this.animalid = animalid == null ? null : animalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.filePath
     *
     * @return the value of cibr_buss_identify.filePath
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.filePath
     *
     * @param filepath the value for cibr_buss_identify.filePath
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.createtime
     *
     * @return the value of cibr_buss_identify.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.createtime
     *
     * @param createtime the value for cibr_buss_identify.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.openId
     *
     * @return the value of cibr_buss_identify.openId
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.openId
     *
     * @param openid the value for cibr_buss_identify.openId
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.latitude
     *
     * @return the value of cibr_buss_identify.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.latitude
     *
     * @param latitude the value for cibr_buss_identify.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.longitude
     *
     * @return the value of cibr_buss_identify.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.longitude
     *
     * @param longitude the value for cibr_buss_identify.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.altitude
     *
     * @return the value of cibr_buss_identify.altitude
     *
     * @mbggenerated
     */
    public String getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.altitude
     *
     * @param altitude the value for cibr_buss_identify.altitude
     *
     * @mbggenerated
     */
    public void setAltitude(String altitude) {
        this.altitude = altitude == null ? null : altitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.recstatus
     *
     * @return the value of cibr_buss_identify.recstatus
     *
     * @mbggenerated
     */
    public String getRecstatus() {
        return recstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.recstatus
     *
     * @param recstatus the value for cibr_buss_identify.recstatus
     *
     * @mbggenerated
     */
    public void setRecstatus(String recstatus) {
        this.recstatus = recstatus == null ? null : recstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.updateTime
     *
     * @return the value of cibr_buss_identify.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.updateTime
     *
     * @param updatetime the value for cibr_buss_identify.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_buss_identify.fileId
     *
     * @return the value of cibr_buss_identify.fileId
     *
     * @mbggenerated
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_buss_identify.fileId
     *
     * @param fileid the value for cibr_buss_identify.fileId
     *
     * @mbggenerated
     */
    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }
}