package com.cibr.InsectRecognition.entity;

import java.util.Date;

public class CibrSysAnimal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.typeId
     *
     * @mbggenerated
     */
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.imgUrl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.curStatus
     *
     * @mbggenerated
     */
    private String curstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.enname
     *
     * @mbggenerated
     */
    private String enname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.feature
     *
     * @mbggenerated
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.biofeature
     *
     * @mbggenerated
     */
    private String biofeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.economic
     *
     * @mbggenerated
     */
    private String economic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_animal.distributed
     *
     * @mbggenerated
     */
    private String distributed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.id
     *
     * @return the value of cibr_sys_animal.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.id
     *
     * @param id the value for cibr_sys_animal.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.name
     *
     * @return the value of cibr_sys_animal.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.name
     *
     * @param name the value for cibr_sys_animal.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.typeId
     *
     * @return the value of cibr_sys_animal.typeId
     *
     * @mbggenerated
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.typeId
     *
     * @param typeid the value for cibr_sys_animal.typeId
     *
     * @mbggenerated
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.imgUrl
     *
     * @return the value of cibr_sys_animal.imgUrl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.imgUrl
     *
     * @param imgurl the value for cibr_sys_animal.imgUrl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.curStatus
     *
     * @return the value of cibr_sys_animal.curStatus
     *
     * @mbggenerated
     */
    public String getCurstatus() {
        return curstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.curStatus
     *
     * @param curstatus the value for cibr_sys_animal.curStatus
     *
     * @mbggenerated
     */
    public void setCurstatus(String curstatus) {
        this.curstatus = curstatus == null ? null : curstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.description
     *
     * @return the value of cibr_sys_animal.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.description
     *
     * @param description the value for cibr_sys_animal.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.createTime
     *
     * @return the value of cibr_sys_animal.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.createTime
     *
     * @param createtime the value for cibr_sys_animal.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.enname
     *
     * @return the value of cibr_sys_animal.enname
     *
     * @mbggenerated
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.enname
     *
     * @param enname the value for cibr_sys_animal.enname
     *
     * @mbggenerated
     */
    public void setEnname(String enname) {
        this.enname = enname == null ? null : enname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.feature
     *
     * @return the value of cibr_sys_animal.feature
     *
     * @mbggenerated
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.feature
     *
     * @param feature the value for cibr_sys_animal.feature
     *
     * @mbggenerated
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.biofeature
     *
     * @return the value of cibr_sys_animal.biofeature
     *
     * @mbggenerated
     */
    public String getBiofeature() {
        return biofeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.biofeature
     *
     * @param biofeature the value for cibr_sys_animal.biofeature
     *
     * @mbggenerated
     */
    public void setBiofeature(String biofeature) {
        this.biofeature = biofeature == null ? null : biofeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.economic
     *
     * @return the value of cibr_sys_animal.economic
     *
     * @mbggenerated
     */
    public String getEconomic() {
        return economic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.economic
     *
     * @param economic the value for cibr_sys_animal.economic
     *
     * @mbggenerated
     */
    public void setEconomic(String economic) {
        this.economic = economic == null ? null : economic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_animal.distributed
     *
     * @return the value of cibr_sys_animal.distributed
     *
     * @mbggenerated
     */
    public String getDistributed() {
        return distributed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_animal.distributed
     *
     * @param distributed the value for cibr_sys_animal.distributed
     *
     * @mbggenerated
     */
    public void setDistributed(String distributed) {
        this.distributed = distributed == null ? null : distributed.trim();
    }
}