package com.cibr.InsectRecognition.dao;

import com.cibr.InsectRecognition.entity.CibrSysType;
import com.cibr.InsectRecognition.entity.CibrSysTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrSysTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int countByExample(CibrSysTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int insert(CibrSysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    List<CibrSysType> selectByExample(CibrSysTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    CibrSysType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysType record, @Param("example") CibrSysTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysType record, @Param("example") CibrSysTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysType record);
}