package com.cibr.InsectRecognition.dao;

import com.cibr.InsectRecognition.entity.CibrSysAnimal;
import com.cibr.InsectRecognition.entity.CibrSysAnimalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrSysAnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int countByExample(CibrSysAnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysAnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int insert(CibrSysAnimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysAnimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    List<CibrSysAnimal> selectByExample(CibrSysAnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    CibrSysAnimal selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysAnimal record, @Param("example") CibrSysAnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysAnimal record, @Param("example") CibrSysAnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysAnimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_animal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysAnimal record);
}