package com.cibr.InsectRecognition.dao;

import com.cibr.InsectRecognition.entity.CibrBussIdentify;
import com.cibr.InsectRecognition.entity.CibrBussIdentifyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrBussIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int countByExample(CibrBussIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int deleteByExample(CibrBussIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int insert(CibrBussIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int insertSelective(CibrBussIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    List<CibrBussIdentify> selectByExample(CibrBussIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    CibrBussIdentify selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrBussIdentify record, @Param("example") CibrBussIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrBussIdentify record, @Param("example") CibrBussIdentifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrBussIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_buss_identify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrBussIdentify record);
}